/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rege.rege.utf8chr.test;

import java.util.logging.Logger;

import rege.rege.utf8chr.UTF8Char;
import rege.rege.utf8chr.UTF8Sequence;

public class Test1 {
    public static final Logger LOGGER =
    Logger.getLogger("rege.rege.utf8chr.test.Test1");

    public static void main(String[] args) {
        final UTF8Sequence HELLO = new UTF8Sequence("Hello world");
        LOGGER.info(HELLO.toString());
        LOGGER.info(HELLO.subSequence(6).toString());
        LOGGER.info(HELLO.subSequence(0, 5).toString());
        LOGGER.info(UTF8Sequence
                    .decodeFrom(new byte[]{-28, -67, -96, -27, -91, -67})
                    .toString());
        LOGGER.info(new UTF8Sequence('!')
                    .join(new UTF8Sequence[]{HELLO, HELLO}).toString());
        LOGGER.info(HELLO.charAt(0).toString());
        LOGGER.info(Boolean.toString(HELLO.subSequence(6)
                                     .equals(new UTF8Sequence("world"))));
        LOGGER.info(Boolean.toString(HELLO.subSequence(6)
                                     .equals(new UTF8Sequence("World"))));
        LOGGER.info(HELLO.toUpperCase().toString());
        LOGGER.info(UTF8Sequence.join(new UTF8Char('!'), HELLO.singles())
                    .toString());
        LOGGER.info(UTF8Sequence
                    .decodeFrom(new byte[]{-28, -67, -96, -27, -91, 33},
                                "surrogateescape").toString());
        LOGGER.info(HELLO.ljust(15, new UTF8Char('!')).toString());
        LOGGER.info(HELLO.rjust(15, new UTF8Char('!')).toString());
        LOGGER.info(HELLO.rjust(15).toString());
        LOGGER.info(HELLO.repeat(5).toString());
        LOGGER.info(HELLO.repeat(1).toString());
        LOGGER.info(HELLO.repeat(-1).toString());
    }
}
